### ISSUE TITLE
[enhancement] Upgrade etcd version

### ISSUE THREAD

**Issue by ary1992** [gardener/etcd-wrapper#29]
With the latest kubernetes release (v1.31), a new mechanism is added to check whether etcd supports a feature or not. More about it can be read here [Implement checking etcd version to warn about deprecated etcd versions](https://github.com/kubernetes/kubernetes/issues/123192)

Not supported version of `etcd`, leads to following messages in the `gardener-apiserver` logs
```
RequestWatchProgress feature is not supported by \"https://etcd-client.garden.svc:2379\" endpoint
```

**Comment by ishan16696** [comment]
Hi @ary1992 ,
We already have a plan to upgrade our etcd's: https://github.com/gardener/etcd-druid/issues/445. Etcd-druid team got aware of this by this issue: https://github.com/gardener/etcd-wrapper/issues/28.  I'm closing this issue in favour of this: https://github.com/gardener/etcd-druid/issues/445
/close
